dist: xenial
language: python
python: 3.7.1

cache:
  directories:
    - node_modules

install:
  - pip install -r requirements-test.txt

script:
  - python tests.py

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
