name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  # Label of the container job
  deploy:
    runs-on: ubuntu-latest

    # if: github.event_name == 'push' # Skip on pull requests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Fly
        run: |
          curl -L https://fly.io/install.sh | sh
      - name: Deploy to Fly
        run: |
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          fly version
          fly auth docker
          bash scripts/deploy.sh
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production